"""Extractor for IA-Invest previdencia snapshot export CSVs.

Generated by :class:`mcp_server.services.portfolio_export.PortfolioExportService`,
this format is a 1:1 dump of the ``previdencia_snapshots`` table.

Re-importing produces records whose shape matches the output of
:class:`extractors.previdencia_ibm_pdf.PrevidenciaIbmPdfExtractor` so the
existing ``_import_previdencia_ibm_file`` flow can consume it without
changes.
"""

from __future__ import annotations

import csv
import io
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Any

from extractors.base import BaseExtractor, ExtractionResult

# Header signature (subset) that uniquely identifies a previdencia export.
SIGNATURE_COLUMNS: frozenset[str] = frozenset(
    {
        "asset_code",
        "product_name",
        "period_month",
        "quantity",
        "unit_price",
        "market_value",
    }
)


def _normalise_header(name: str) -> str:
    return (name or "").strip().lower()


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")


def _to_cents(value: str | None) -> int:
    if value is None or value == "":
        return 0
    try:
        return int((Decimal(value) * 100).quantize(Decimal("1")))
    except (InvalidOperation, ValueError) as exc:
        raise ValueError(f"Invalid monetary value: {value!r}") from exc


def is_ia_invest_previdencia_export_csv(path: Path) -> bool:
    """Detect IA-Invest previdencia export CSVs by header signature."""
    if path.suffix.lower() not in {".csv", ".txt"}:
        return False
    try:
        text = _read_text(path)
    except OSError:
        return False
    sample = text[:4096]
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
    except csv.Error:
        dialect = csv.excel
    reader = csv.reader(text.splitlines(), dialect=dialect)
    try:
        header = next(reader)
    except StopIteration:
        return False
    normalised = {_normalise_header(c) for c in header if c}
    return SIGNATURE_COLUMNS.issubset(normalised)


class IaInvestPrevidenciaExportCsvExtractor(BaseExtractor):
    """Reads back previdencia CSV files produced by ``PortfolioExportService``."""

    source_type = "ia_invest_previdencia_export_csv"

    def can_handle(self, file_path: Path) -> bool:
        return is_ia_invest_previdencia_export_csv(file_path)

    def extract(self, file_path: Path) -> ExtractionResult:
        result = ExtractionResult(source_type=self.source_type)
        try:
            text = _read_text(file_path)
        except Exception as exc:  # noqa: BLE001
            result.errors.append({
                "row_index": None,
                "error_type": "parsing",
                "message": f"Could not read CSV file: {exc}",
            })
            return result

        try:
            dialect = csv.Sniffer().sniff(text[:4096], delimiters=",;\t")
        except csv.Error:
            dialect = csv.excel

        reader = csv.DictReader(io.StringIO(text), dialect=dialect)
        if reader.fieldnames is None:
            result.errors.append({
                "row_index": None,
                "error_type": "parsing",
                "message": "CSV has no header row or is empty.",
            })
            return result

        header_map = {
            original: _normalise_header(original) for original in reader.fieldnames
        }

        for row_index, raw_row in enumerate(reader):
            if not any((v or "").strip() for v in raw_row.values() if isinstance(v, str)):
                continue
            row: dict[str, str | None] = {}
            for original_key, value in raw_row.items():
                canonical = header_map.get(original_key, _normalise_header(original_key))
                if isinstance(value, str):
                    value = value.strip()
                if value == "":
                    value = None
                row[canonical] = value

            try:
                quantity = float(row.get("quantity") or 0)
                unit_price_cents = _to_cents(row.get("unit_price"))
                market_value_raw = row.get("market_value")
                if market_value_raw:
                    market_value_cents = _to_cents(market_value_raw)
                else:
                    market_value_cents = int(round(quantity * unit_price_cents))
            except ValueError as exc:
                result.errors.append({
                    "row_index": row_index,
                    "error_type": "parsing",
                    "message": str(exc),
                    "raw_data": dict(raw_row),
                })
                continue

            asset_code = row.get("asset_code")
            product_name = row.get("product_name")
            period_month = row.get("period_month")
            if not asset_code or not product_name or not period_month:
                result.errors.append({
                    "row_index": row_index,
                    "error_type": "validation",
                    "message": "Missing required column (asset_code, product_name, period_month).",
                    "raw_data": dict(raw_row),
                })
                continue

            record: dict[str, Any] = {
                "asset_code": asset_code,
                "product_name": product_name,
                "period_month": period_month,
                "period_start_date": row.get("period_start_date"),
                "period_end_date": row.get("period_end_date"),
                "quantity": quantity,
                "unit_price_cents": unit_price_cents,
                "market_value_cents": market_value_cents,
                "source_file": row.get("source_file") or file_path.name,
            }
            result.records.append(record)

        return result
