"""Extractor for IA-Invest canonical export CSVs.

Generated by :class:`mcp_server.services.portfolio_export.PortfolioExportService`,
this format is a 1:1 dump of the ``operations`` table with snake_case
canonical column names and BRL monetary values rendered as decimal reais
(``"12.34"`` for 1234 cents).

The extractor preserves the ``source`` and ``external_id`` columns verbatim
so re-importing produces operations identical to the originals.

Quote-leg generation (binance) is intentionally NOT triggered: every leg
is already a row in the export, and ``quote_currency`` is omitted from
the header so :class:`OperationNormalizer` will not synthesise extra rows.
"""

from __future__ import annotations

import csv
import io
from pathlib import Path
from typing import Any

from extractors.base import BaseExtractor, ExtractionResult

# Columns that must be present (in any order) for the file to be
# considered an IA-Invest export CSV. Matches
# :data:`mcp_server.services.portfolio_export.OPERATIONS_HEADER`.
SIGNATURE_COLUMNS: frozenset[str] = frozenset(
    {
        "source",
        "external_id",
        "asset_code",
        "asset_type",
        "operation_type",
        "operation_date",
        "quantity",
        "unit_price",
        "gross_value",
        "trade_currency",
    }
)


def _normalise_header(name: str) -> str:
    return (name or "").strip().lower()


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")


def is_ia_invest_export_csv(path: Path) -> bool:
    """Detect IA-Invest export CSVs by header signature."""
    if path.suffix.lower() not in {".csv", ".txt"}:
        return False
    try:
        text = _read_text(path)
    except OSError:
        return False
    sample = text[:4096]
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=",;\t")
    except csv.Error:
        dialect = csv.excel
    reader = csv.reader(text.splitlines(), dialect=dialect)
    try:
        header = next(reader)
    except StopIteration:
        return False
    normalised = {_normalise_header(c) for c in header if c}
    return SIGNATURE_COLUMNS.issubset(normalised)


class IaInvestExportCsvExtractor(BaseExtractor):
    """Reads back CSV files produced by ``PortfolioExportService``."""

    source_type = "ia_invest_export_csv"

    def can_handle(self, file_path: Path) -> bool:
        return is_ia_invest_export_csv(file_path)

    def extract(self, file_path: Path) -> ExtractionResult:
        result = ExtractionResult(source_type=self.source_type)
        try:
            text = _read_text(file_path)
        except Exception as exc:  # noqa: BLE001
            result.errors.append({
                "row_index": None,
                "error_type": "parsing",
                "message": f"Could not read CSV file: {exc}",
            })
            return result

        try:
            dialect = csv.Sniffer().sniff(text[:4096], delimiters=",;\t")
        except csv.Error:
            dialect = csv.excel

        reader = csv.DictReader(io.StringIO(text), dialect=dialect)
        if reader.fieldnames is None:
            result.errors.append({
                "row_index": None,
                "error_type": "parsing",
                "message": "CSV has no header row or is empty.",
            })
            return result

        header_map = {
            original: _normalise_header(original) for original in reader.fieldnames
        }

        for raw_row in reader:
            if not any((v or "").strip() for v in raw_row.values() if isinstance(v, str)):
                continue
            record: dict[str, Any] = {"file_name": file_path.name}
            for original_key, value in raw_row.items():
                canonical = header_map.get(original_key, _normalise_header(original_key))
                if isinstance(value, str):
                    value = value.strip()
                if value == "":
                    value = None
                record[canonical] = value
            # Preserve original source if the row didn't include one.
            record.setdefault("source", "ia_invest_export_csv")
            result.records.append(record)

        return result
